### ISSUE TITLE
cannot import name 'postpy2' from 'postpy2.core'

### ISSUE THREAD

**Issue by gonazmul** [matkapi/postpython#2]
When I run following python file -
```
#!/usr/local/lib/python3.8
from postpy2.core import postpy2
def main():
	print("test")
	main()
```

I get following error -
```
Traceback (most recent call last):
  File "aaa.py", line 2, in <module>
    from postpy2.core import postpy2
ImportError: cannot import name 'postpy2' from 'postpy2.core' (/usr/local/lib/python3.8/site-packages/postpy2/core.py)
```

**Comment by michael-hll** [comment]
I encounter the same issue today. My python version is 3.8.1

**Comment by zetc0de** [comment]
try this

`from postpy2.core import PostPython`

**Comment by gonazmul** [comment]
> try this
> 
> `from postpy2.core import PostPython`

This seems to be working but why is the readme says `from postpy2.core import postpy2`. Is it specific to python version or something? I was using pip3 and python version 3.9
